[AEROGEAR-2184] Add check if client exists before deleting it
aerogearcatalog/ios-app-apb pull request #6
Opened 2018-03-13 10:44 UTC by JameelB

## Description
Add a check if the client exists before attempting to delete it. If the client has already been removed, skip the deletion.

## Progress
- [ ] Add check if client exists before deleting

## Additional Notes
Related JIRA Ticket - https://issues.jboss.org/browse/AEROGEAR-2184

2018-03-13 14:45 UTC, ghost requested changes

2018-03-13 14:45 UTC, vchepeli commented on roles/deprovision-ios-app/tasks/main.yml
> +  failed_when: mobile_client.stdout == "" and not mobile_client.stderr | search({{ app_not_found_err }})
use not () e.g. not (mobile_client.stderr | search(app_not_found_err) and you dont need to use {[...}} inside failed_when statement

2018-03-13 14:45 UTC, vchepeli commented on roles/deprovision-ios-app/tasks/main.yml
> +- set_fact: app_not_found_err="'mobileclients.mobile.k8s.io \"{{ appName }}-ios\" not found'"
This can be set_fact: app_not_found_err='mobileclients.mobile.k8s.io "{{ appName }}-android" not found'

2018-03-13 14:45 UTC, vchepeli commented on roles/deprovision-ios-app/tasks/main.yml
> +  when: mobile_client.stderr == ""
you can also use mobile_client.stderr|length == 0 but it should be defined

2018-03-13 16:01 UTC, maleck13 approved these changes
looks good

2018-03-14 10:22 UTC, ghost approved these changes

2018-03-14 10:48 UTC, merged